import streamlit as st
import tensorflow as tf
import os
import requests
import gdown
import rioxarray as rxr


MODEL_URL = "https://drive.google.com/uc?id=1dwRQJytS7qidRt4bhGYz2MDKBlzn8XCQ"
MODEL_PATH = "cloud_removal_model.h5"

@st.cache_resource
def download_and_load_model():
    if not os.path.exists(MODEL_PATH):
        with st.spinner("Downloading model from Google Drive..."):
            gdown.download(id=MODEL_ID, output=MODEL_PATH, quiet=False)
    return tf.keras.models.load_model(MODEL_PATH)

model = download_and_load_model()

# Utility: preprocess input image
def preprocess_image(img):
    img = normalized_cloud_free = 2 * (np.array(img) - np.array(img).min()) / (np.array(img).max() - np.array(img).min()) - 1
    img = np.expand_dims(img, axis = 0)
    return img

# Utility: postprocess output image
def postprocess_image(pred):
    pred = ((pred + 1) / 2)**0.4
    return pred

# Streamlit UI
st.title("☁️→🌤️ Cloud Removal App")
st.write("Upload a cloudy satellite image to see a cloud-free version generated by the model.")

uploaded_file = st.file_uploader("Upload Cloudy Image", type=["jpg", "jpeg", "png", "tif", "tiff"])

if uploaded_file:
    input_image = rxr.open_rasterio(uploaded_file)
    st.image(input_image, caption="Input: Cloudy Image", use_column_width=True)

    with st.spinner("Generating cloud-free image..."):
        input_tensor = preprocess_image(input_image)
        output_tensor = model.predict(input_tensor)
        output_image = postprocess_image(output_tensor)

    st.image(output_image, caption="Output: Cloud-Free Image", use_column_width=True)




